Update color palette
sanity-io/ui pull request #1137
Opened 2023-09-19 06:46 UTC by pedrobonamin

## Color palette updates
With the updates proposed to facelift, the color palette now needs to support different tones and different tints for each mode and type of use.

Examples of different colors in same tone.
-  base background color for the `active` is **white**, even though the base color for `active` is **cyan**.
-  base background color:hover for the `active` is **gray 50**, even though the base color for `active` is **cyan**.

<img width="282" alt="Screenshot 2023-09-19 at 08 42 54" src="https://github.com/sanity-io/ui/assets/46196328/da1f56a3-ad1f-495d-9c26-b52e13bb8f3a">

Examples of different tints across tones:
- Accent background: 
  - Default uses **gray 900** (hue in tint 900)
  - Active uses **cyan 400** (hue in tint 400)
  - Critical and caution use **red 500** and **yellow 500** (hue in tint 500)
 
<img width="903" alt="Screenshot 2023-09-19 at 08 43 14" src="https://github.com/sanity-io/ui/assets/46196328/4757f8f0-71ad-4dc7-aec3-c365a90e2e9d">

## Extra
Adds base story with buttons matrix, this is a work in progress to validate the colors palette updates and button updates.

<img width="500" alt="Screenshot 2023-09-19 at 08 45 31" src="https://github.com/sanity-io/ui/assets/46196328/16e41e29-8f68-4a04-85f2-eb1fa3dc9be1">

2023-10-01 09:51 UTC, robinpyon requested changes
Thanks @pedrobonamin! I didn't index on button styling changes in this review – since the focus of this PR is updating colors – and there's an [another in-flight PR](https://github.com/sanity-io/ui/pull/1142) which deals with those.

2023-10-02 07:24 UTC, pedrobonamin commented on src/theme/studioTheme/tints.ts
> +type colorsKeys =
Thanks! will replace for `ColorKey`,  given `ColorTintKey` is already defined in `@sanity/color`

2023-10-02 07:31 UTC, pedrobonamin commented on stories/helpers/matrixBuilder.tsx
> +  scheme: 'light' | 'dark'
Great question and I think it's worth discussing it.
I found an added value in setting the scheme prop and representing the two schemes in the same story, given that when you are changing the colors and updating the component you can detect in a glance if theres something missing or wrong. 

Also, thinking in if we add visual testing, both scenarios can be tested with the same story.

2023-10-02 07:41 UTC, pedrobonamin commented on stories/primitives/Button.stories.tsx
> +        scheme: 'light',
Removing this added story, will handle in the next PR. It was worth having it here before the creation of the PR as it was a way to test the color updates.

2023-10-02 07:58 UTC, robinpyon commented on stories/helpers/matrixBuilder.tsx
> +  scheme: 'light' | 'dark'
That's fair! Perhaps then this is something we limit to these larger "multiple styles" stories only (which show _everything_ at once).

2023-10-02 10:53 UTC, pedrobonamin commented on src/theme/studioTheme/tints.ts
> +}
Added a comment, let me know what you think.
Keen to add any suggestion!

2023-10-02 10:55 UTC, pedrobonamin commented on stories/helpers/matrixBuilder.tsx
> +  scheme: 'light' | 'dark'
We can make it an optional prop if we want to use it for "large" and "smaller" stories, and it can infer it from the current theme, that is the behaviour of cards if no theme prop is provided, will add that change.

2023-10-02 12:28 UTC, robinpyon commented on src/theme/studioTheme/tints.ts
> +}
Thanks, this definitely helps!

2023-10-02 12:32 UTC, robinpyon approved these changes
Thanks @pedrobonamin! The studio colors story is very much welcome

In future, perhaps we may want to consider separating the **Studio Colors** story into a specific 'Studio UI' section, since it's really only specific to the Studio implementation right now

2023-10-02 12:54 UTC, merged